---
title: "R Notebook"
output: html_notebook
---

### Spurningar / vangaveltur /nótur

1. Hver er dreifing fjölda atburðanna?
2. Hverjar er líkurnar á því að atburður eigi sér stað fyrir gefna sögu?
3. Munur á því að skoða endurinnlögn og endurinnlögn VEGNA greiningar (multivariate event). Það er hægt að ímynda sér að tími á milli og tíðni innlagna er háð greiningu.
5. Skipting skýribreyta í innri (háð hegðun einstaklings) og ytri (óháð hegðun einstaklings) breytur.
6. Fara líkindi á endurinnlögn dvínandi með tíma?
7. Hvað skal gera vegna dauða (valbjögun)
8. Hvert er samband á milli dvalartíma, tíðni endurinnlagna og tíma milli endurinnlagna fyrir gefinn sjúkdóm?
9. Hver er dreifing dvalartíma og tíma á milli endurinnlagna?
10. Eru dvalartími og tími milli endurinnlagna óháðar stærðir?

### Hugleiðingar á rannsókn
Sögulegum gögnum var safnað um bráðar endurinnlagnir á legudeildir geðsviðs Landspítalans. Rannsóknartímabilið eru innlagnir á árunum 2007 - 2017. Þar sem sami einstaklingur gat verið lagður inn ítrekað á tímabilinu er rannsóknin afturvirk langsniðsrannsókn með paraðar mælingar.

Atburðurinn sem skal rannsaka er endurinnlögn. Ljóst er að þegar einstaklingur er inn á legudeild þá eru engar líkur á endurinnlögn. Einstaklingur er því aðeins í hættu á endurinnlögn eftir útskrift. Tímakvarðinn er rannsóknartímabilið en upphafspunktur talningarferlis hvers einstaklings er fyrsta innlögn. Hætt er að fylgjast með einstakling þegar:

1. Rannsóknartímabilinu lýkur eða einstaklingur hverfur.
2. Annar atburður sem bindur enda á eftirfylgni, til að mynda dauðsfall.

Ef atburður eins og dauði er háður sjúkrasögu einstaklings á valbjögun sér stað.

Dvalartími og tími milli endurinnlagnar eru tvær breytur sem vert er að skoða. Eru sjúklingar sem útskrifast eftir stutta dvöl líklegri til að koma aftur fyrr? Hver er tíðni endurinnlagna hjá einstaklingum sem dvelja stutt? Hvað er átt við með stutt? Hvert er samband á milli dvalartíma, tíðni endurinnlagna og tíma milli endurinnlagna fyrir gefinn sjúkdóm? Eru einstaklingar með gefinn sjúkdóm einsleitir hvað varðar endurinnlögn og dvalartíma?

Ef við lítum á dvalartíma og tíma milli endurinnlagnar sem ástönd er hægt að skoða hvernig einstaklingur færist á milli þessara tveggja ástanda. Til að mynda, ef dvalartími er virkt ástand þar sem sjúkdómurinn er 'virkur'; tími á milli endurinnlagnar er hins vegar óvirkt ástand þar sjúklingur er í hættu á endurinnlögn.

Aftur þarf að taka tillit til atburða sem binda enda á endurkomur (dauði).

### Líkön
1. Líkan sem skoðar biðtíma á milli endurinnlagna.
2. Líkan sem skoðar dvalartíma og tíma á milli endurinnlagna sér í lagi
3. Líkan sem skoðar dvalartíma og tíma á milli endurinnlagna sem tvö ástönd sem sjúklingur ferðast á milli.
4. Sama líkan og líkan 2 með viðbættu þriðja ástandi sem er gleypið (dauði).

## Fræði (i vinnslu)

### Talningarferli, sögufall og magnfall
Látum $N(s,t)$ tákna fjölda tilfella af atburði yfr tímabil $(s, t]$ fyrir einstakling. Gerum ráð fyrir að talning hefst á tíma $t = 0$ þar sem $N(0) = 0$ og skilgreinum $N(t) = N(0, t)$ þar sem $t > 0$. Ferlið $\{N(t), 0 \leq t \}$ kallast þá talningarferli atburðs.

Skilgreinum sögufall atburðarrásar $H(t)$ þannig að
$$
H(t) = \{N(s): 0 \leq s < t\} \quad t > 0,
$$
og táknum fjölda tilfella af atburði  á tímabili $[t, t + \Delta)$ með $\Delta N(t) = N(t + \Delta t^-) - N(t^-)$

Fyrir atburði sem eiga sér stað í samfelldum tíma gerum við ráð fyrir því að tveir atburðir geta ekki átt sér stað samtímis. Magnfall $\lambda(t|H(t))$ atburða er skilgreint sem
$$
\lambda(t|H(t)) = \lim _{\Delta t \to 0} \frac{\mathbb{P}(\Delta N(t) = 1|H(t))}{\Delta t}.
$$
Það er, magnfallið gefur líkindin á því að atburður eigi sér stað á tíma $t$, skilyrt á sögu ferlsins. Magnfallið mun skilgreina ferli atburða og öll einkenni ferla má ákvarða frá því.

Skilgreinum biðtíma $W_j = T_j - T_{j-1}$, $j = (1, 2, \ldots)$ þar sem $T_k$ er tíminn þegar atburður $k$ átti sér stað. Endurnýjunarferli (e. renewal process) er ferli þar sem biðtímar $W_j$ milli atburða eru óháðir og eindreifðir.

Þetta jafngildir skilyrðinu að intensity fallið sé
\begin{equation}
\lambda(t|H(t)) = h(B(t)) \quad t > 0.
\end{equation}
Hér er $B(t)$ tíminn síðan síðasti atburður átti sér stað, það er, $B(t) = t - T_{N(t^-)}$ og $h(w))$ er hættufall (e. hazard function) $W_j$.

Þar sem $W_j$ eru einsdreifðar og óháðar slembistærðir hafa þau öll sama þéttifall $f(w)$ og lifunarfall $S(w) = \mathbb{P}(W \geq w)$ og
\begin{equation}
h(w) = \frac{f(w)}{S(w)} = \lim _{\Delta w \to 0} \frac{\mathbb{P}(W < w + \Delta w| W \geq w)}{\Delta w}
\end{equation}

Þar sem biðtímar $W_j$ eru jákvæðar stærðir er hægt að meta endurnýjunarferli með tvennskonar líkönum:

* *Proportional hazard* líkan þar sem hættufall $W_j$ fyrir gefnar skýribreytur $z$ (óháðar tíma) er 
$$
h(w|z) = h_0(w)\exp (z^T\beta),
$$

* *Accelerated failure time model* þar sem hættufallið er
$$
h(w|z) = h_0(we^{z^T \beta}) \exp(z^T\beta)
$$

Í báðum tilfellum er $h_0(w)$ grunnhættufallið.

Ef einhverjar skýribreytur eru háðar tíma, það er, $z(t)$ er hægt að hugleiða endurnýjunarferli með intensity fall
$$
\lambda(t|H(t)) = h(B(t)|z(t)).
$$
Hættufallið verður þá
$$
h(w|z(t)) = h_0(w)\exp(z^T(t)\beta),
$$

þar sem $t = w + t_{N(t^-)}$. Hér er aftur gert ráð fyrir því að $W_j$ séu óháðar slembistærðir en þær þurfa hins vegar ekki að vera einsdreifðar.

Forsendan um einsdreifða biðtíma er fullsterk. 

1. Skilgreinum $Y_i = \log(W_j)$ fyrir $W_j$ gefið $W_1, \ldots , W_{j-1}$ og skýribreytu $z$ (óháð tíma). Þá er $W_j$ sögð vera log-normaldreifð, skilyrt á fyrri biðtíma og skýribreytur.

2. Ef við leyfum $z(t)$ að innihalda fyrri biðtíma eða fjölda fyrri atburða. Þá er $w = B(t)$ sá tími sem hefur liðið frá síðasta atburði 

Ef við gerum ráð fyrir því að $W_j$ er slembistærð skilyrt á $W_1, W_2, \ldots , W_{j-1}$ og $z$ er hentugt að skilgreina $Y_j = \log (W_j)$

To-do:

2. Nefna líkön sem gera ekki ráð fyrir einsdreifðum $W_j$
3. Nefna random effects líkön.
4. Nefna líkön þar sem $W_j$ eru ekki óháð
4. Búa til spurningarlista fyrir Thor, Sigrúnu, Ragnar.
